const fs = require('fs');
const path = require('path');

const scrapersDir = path.join(__dirname, 'scrapers', 'cities', 'vancouver');

const scraperFiles = [
  'anthropologyMuseumEvents.js',
  'arcDiningEvents.js',
  'artGalleryEvents.js',
  'barNoneClub.js',
  'bardOnTheBeach.js',
  'bardOnTheBeachEvents.js',
  'bcPlaceEvents.js',
  'bcPlaceStadium.js',
  'billReidGalleryEvents.js',
  'biltmoreCabaret.js',
  'biltmoreCabaretEvents.js',
  'broadwayVancouverEvents.js',
  'canadaPlaceEvents.js',
  'capilanoSuspensionBridge.js',
  'carnavalDelSol.js',
  'celebritiesNightclub.js',
  'chanCentre.js',
  'chanCentreEvents.js',
  'cherryBlossomFestEvents.js',
  'chineseGardenEvents.js',
  'coastalJazzEvents.js',
  'coastalJazzFestival.js',
  'commodoreBallroomEvents.js',
  'contemporaryArtGalleryEvents.js',
  'cultureCrawlEvents.js',
  'danceFestivalEvents.js',
  'doxaFilmFestivalEvents.js',
  'dragonBoatFestivalEvents.js',
  'festivalDEteEvents.js',
  'folkFestEvents.js',
  'fortuneSoundClub.js',
  'fortuneSoundClubBridge.js',
  'foxCabaret.js',
  'fringeFestivalEvents.js',
  'gastownGrandPrixEvents.js',
  'gastownSundaySet.js',
  'granvilleIsland.js',
  'granvilleIslandEvents.js',
  'granvilleIslandMarket.js',
  'granvilleMarketEvents.js',
  'harbourEventCentre.js',
  'helloBCEvents.js',
  'helloBCEventsAdditional.js',
  'helloBCEventsScraper.js',
  'helloGoodbyeBarEvents.js',
  'hrMacMillanSpaceCentre.js',
  'hrMacMillanSpaceCentreEvents.js',
  'imperialTheatre.js',
  'improvCentreEvents.js',
  'irishHeather.js',
  'japanMarketEvents.js',
  'junctionPublicMarket.js',
  'khatsahlanoEvents.js',
  'kitsilanoShowboat.js',
  'laowaiBar.js',
  'levelsNightclub.js',
  'macMillanSpaceCentreEvents.js',
  'malonesEvents.js',
  'maritimeMuseumEvents.js',
  'metropolisEvents.js',
  'moaUbcEvents.js',
  'museumOfAnthropology.js',
  'museumOfAnthropologyEvents.js',
  'museumOfVancouver.js',
  'museumOfVancouverEvents.js',
  'musqueamEvents.js',
  'orpheumEvents.js',
  'orpheumTheatre.js',
  'orpheumTheatreEvents.js',
  'pneEvents.js',
  'pneFair.js',
  'pneSummerNightConcerts.js',
  'polygonGallery.js',
  'publicLibraryEvents.js',
  'queenElizabethTheatre.js',
  'queenElizabethTheatreEvents.js',
  'queerArtsFestivalEvents.js',
  'queerFilmFestivalEvents.js',
  'redRoom.js',
  'redRoomEvents.js',
  'richmondNightMarket.js',
  'rickshawTheatreEvents.js',
  'runToEndEndoEvents.js',
  'scienceWorld.js',
  'scienceWorldEvents.js',
  'scienceWorldVancouverEvents.js',
  'shipyardsNightMarket.js',
  'spaceCenter.js',
  'spaceCentreEvents.js',
  'squamishBeerFestival.js',
  'stanleyPark.js',
  'stanleyParkEvents.js',
  'steamworksBrewing.js',
  'steamworksBrewingEvents.js',
  'summerCinemaEvents.js',
  'theCentreVancouver.js',
  'theCultchEvents.js',
  'thePearlEvents.js',
  'theRoxyEvents.js',
  'theatreUnderTheStars.js',
  'theatreUnderTheStarsEvents.js',
  'tourismVancouverEvents.js',
  'ubcBotanicalGardenEvents.js',
  'undergroundComedyClubEvents.js',
  'vancouverAquarium.js',
  'vancouverAquariumEvents.js',
  'vancouverArtAndLeisure.js',
  'vancouverArtGallery.js',
  'vancouverArtGalleryEvents.js',
  'vancouverAsianFilmFestivalEvents.js',
  'vancouverCityEvents.js',
  'vancouverCivicTheatres.js',
  'vancouverConventionCentreEvents.js',
  'vancouverFilmFestivalEvents.js',
  'vancouverFolkFest.js',
  'vancouverFringe.js',
  'vancouverInternationalFilmFestival.js',
  'vancouverJazzFestEvents.js',
  'vancouverJazzFestival.js',
  'vancouverMaritimeMuseumEvents.js',
  'vancouverMysteriesEvents.js',
  'vancouverPride.js',
  'vancouverSymphony.js',
  'vancouverSymphonyEvents.js',
  'veganMarketEvents.js',
  'venueNightclub.js',
  'vogueTheatre.js',
  'vogueTheatreEvents.js',
  'vsffEvents.js',
  'westernFrontEvents.js',
  'wiseHall.js',
  'yaletownJazz.js'
];

async function runScrapers() {
  for (const file of scraperFiles) {
    const scraperPath = path.join(scrapersDir, file);
    try {
      const ScraperClass = require(scraperPath);
      const scraper = new ScraperClass();
      console.log(`\n--- Running scraper: ${scraper.name} from ${file} ---`);
      const events = await scraper.scrape();
      console.log(`Found ${events.length} events.`);
      console.log(JSON.stringify(events, null, 2));
    } catch (error) {
      console.error(`\n--- Error running scraper from ${file} ---`);
      console.error(error);
    }
  }
}

runScrapers();
